# Generated by Django 4.1.7 on 2023-04-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rate',
            field=models.IntegerField(max_length=10),
        ),
    ]
