# Generated by Django 4.1.7 on 2023-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_record_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload'),
        ),
    ]
