# Generated by Django 4.1.7 on 2023-04-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_record_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
